server:
  port: 8081

spring:
  datasource:
    name: xlt-ds
    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      primary: db1 # 配置默认数据库
      datasource:
        db1: # 数据源1配置
          url: jdbc:mysql://localhost:3306/xlt?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
        db2: # 数据源2配置
          url: jdbc:mysql://192.168.26.128:8066/TEST?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
    druid:  #druid相关配置
      filters: stat #监控统计拦截的filters
      initial-size: 1  #配置初始化大小/最小/最大
      min-idle: 1
      max-active: 20
      max-wait: 60000 #获取连接等待超时时间
      time-between-eviction-runs-millis: 60000  #间隔多久进行一次检测，检测需要关闭的空闲连接
      min-evictable-idle-time-millis: 300000  #一个连接在池中最小生存的时间
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      max-pool-prepared-statement-per-connection-size: 20
  redis: # redis配置
    host: 192.168.26.128
    port: 6379
#    password: xlt
    database: 0
    lettuce:
      pool:
        # 连接池最大连接数 默认8 ，负数表示没有限制
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
        max-wait: -1
        # 连接池中的最大空闲连接 默认8
        max-idle: 8
        # 连接池中的最小空闲连接 默认0
        min-idle: 0
  rabbitmq: #MQ配置
    host: 127.0.0.1
    port: 5672
    username: root
    password: root
    # 虚拟host 可以不设置,使用server默认host
    virtual-host: JCcccHost
  #邮箱设置
  mail:
    host: smtp.qq.com
    username: 2219321592@qq.com
    #邮箱授权码
    password: fxnnepfmwenfdhhh
    default-encoding: UTF-8
    form: ${spring.mail.username}
    protocol: smtp
    port: 465
    properties:
      mail:
        debug: true
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath*:com/xxx/xlt/mapper/*.xml
  type-aliases-package: com.xxx.xlt.model

### log4j2配置
logging:
  config: classpath:log/log4j2.xml

http_pool:
  max_total: 200
  default_max_per_route: 100
  connect_timeout: 5000
  connection_request_timeout: 1000
  socket_timeout: 65000
  validate_after_inactivity: 2000

# 分布式调度任务配置
xxl:
  job:
    # 执行器通讯TOKEN [选填]：非空时启用；
    accessToken:
    admin:
      # 调度中心部署跟地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和
      # "任务结果回调"；为空则关闭自动注册；
      addresses: http://192.168.26.128:8088/xxl-job-admin
    executor:
      # 执行器AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
      appname: alexonPlatform
      # 执行器注册 [选填]：优先使用该配置作为注册地址，为空时使用内嵌服务 ”IP:PORT“ 作为注册地址。从而更灵活的支持容器类型执
      # 行器动态IP和动态映射端口问题。
      address:
      # 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于
      # "执行器注册" 和 "调度中心请求并触发任务"；
      ip: 192.168.3.18
      # 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
      port: 8082
      # 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
      logpath: /applogs/xxl-job/jobhandler
      # 执行器日志文件保存天数 [选填] ： 过期日志自动清理, 限制值大于等于3时生效; 否则, 如-1, 关闭自动清理功能；
      logretentiondays: 30

person:
  name: xlt
  number: 00498628


#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check


